easy_admin:
    entities:
      Support:
        class: App\Entity\Support
        form:
          fields:
            - title
            - description
            - { property: 'company' , type: 'easyadmin_autocomplete' ,type_options: { class: 'App\Entity\Company' } }
      Company:
        class: App\Entity\Company
        fields:
          - id
          - label
          - isActive
      Project:
        class: App\Entity\Project
        fields:
          - id
          - nom
          - status

