twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form-themes:
        - bootstrap_4_layout.html.twig
    date:
      #format: d/m/Y, H:i:s
      timezone: Europe/Paris
